#!/bin/bash

usage()
{
  echo "Usage: kubelx [provision|destroy]"
  exit 1
}

NODES="kmaster kworker1 kworker2"

kubeprovision()
{
  # check if we have k8s profile or create one
  lxc profile list | grep -qo kubernetes || (lxc profile create kubernetes && cat kubernetes-config | lxc profile edit kubernetes)
  echo
  for node in $NODES
  do
    echo "==> Bringing up $node"
    lxc launch images:centos/7 $node --profile kubernetes
    sleep 10
    echo "==> Running provisioner script"
    cat bootstrap.sh | lxc exec $node bash
    echo
  done
}

kubedestroy()
{
  for node in $NODES
  do
    echo "==> Destroying $node..."
    lxc delete --force $node
  done
}

case "$1" in
  provision)
    echo -e "\nProvisioning Kubernetes Cluster...\n"
    kubeprovision
    ;;
  destroy)
    echo -e "\nDestroying Kubernetes Cluster...\n"
    kubedestroy
    ;;
  *)
    usage
    ;;
esac